Mku020/implement tab component
appello-software/mobile-ui pull request #4
Opened 2023-11-15 14:19 UTC by VictorPulzz

1. Add HorizontalTabs component
2. Add 2 loaders: Circle and Points
3. Upgrade ESlint version

2023-11-21 18:17 UTC, kuzkokov commented on src/components/common/HorizontalTabs/index.tsx
> +};
может, сразу в коммон кинем?

2023-11-21 18:17 UTC, kuzkokov commented on src/components/index.ts
> +export * from './common/HorizontalTabs';
я тут экспортил не все, чтобы `use*Style` наружу не торчали.
поэтому предлагаю привести здесь все к единому виду все-таки

2023-11-21 18:17 UTC, kuzkokov commented on src/components/common/HorizontalTabs/index.tsx
> +}
напиши еще плиз доку для компонентов и пропсов в виде комментариев (глянь в других компонентах). они потом сами в сторибук подтянутся

2023-11-21 18:17 UTC, kuzkokov commented on .storybook/stories/HorizontalTabs/HorizontalTabs.stories.tsx
> +  },
по-хорошему, в историях еще бы дефолтные значения пропсов описать + чекни, все ли контролы корректно отображаются

2023-11-22 12:17 UTC, VictorPulzz commented on src/components/common/HorizontalTabs/index.tsx
> +};
Окич вынесу

2023-11-22 12:18 UTC, VictorPulzz commented on src/components/common/HorizontalTabs/index.tsx
> +}
А понял, гуд

2023-11-22 12:18 UTC, VictorPulzz commented on .storybook/stories/HorizontalTabs/HorizontalTabs.stories.tsx
> +  },
Оки

2023-11-23 15:15 UTC, kuzkokov commented
@VictorPulzz бабахни еще лоадер в кнопку плиз заодно, а пакет можно тогда удалить

2023-11-23 15:32 UTC, VictorPulzz commented
> @VictorPulzz бабахни еще лоадер в кнопку плиз заодно, а пакет можно тогда удалить

ez :)

2023-11-23 18:09 UTC, VictorPulzz commented on src/components/common/HorizontalTabs/index.tsx
> +};
done

2023-11-23 18:09 UTC, VictorPulzz commented on src/components/index.ts
> +export * from './common/HorizontalTabs';
done

2023-11-23 18:09 UTC, VictorPulzz commented on src/components/common/HorizontalTabs/index.tsx
> +}
done

2023-11-23 18:09 UTC, VictorPulzz commented on .storybook/stories/HorizontalTabs/HorizontalTabs.stories.tsx
> +  },
done

2023-11-23 18:09 UTC, VictorPulzz commented
@kuzkokov Ну усе, можем пихать ето в main :)

2023-12-01 16:41 UTC, kuzkokov requested changes

2023-12-01 16:41 UTC, kuzkokov commented on .storybook/stories/HorizontalTabs/HorizontalTabs.stories.tsx
> +  },
@VictorPulzz а я что-то дефолтных значений здесь не увидел, которые в компоненте есть (типа `tabHeight` и парочка других)

2023-12-01 16:41 UTC, kuzkokov commented on .storybook/stories/Loaders/Circle.stories.tsx
> +  },
здесь render необязателен, если мы какие-то доп.свойства не прокидываем сами. ну это так, fyi

2023-12-01 16:41 UTC, kuzkokov commented on .storybook/stories/Loaders/Circle.stories.tsx
> +  },
\+ тоже не увидел прописанных дефолтных значений

2023-12-01 16:41 UTC, kuzkokov commented on .storybook/stories/Loaders/Points.stories.tsx
> +  },
и здесь нет дефолтных значений

2023-12-01 16:41 UTC, kuzkokov commented on src/components/common/Button/index.tsx
> +      {!isLoading ? label : <Points size={30} />}
а зачем тут цвет потерялся и размер изменился?

2023-12-05 13:16 UTC, VictorPulzz commented on .storybook/stories/HorizontalTabs/HorizontalTabs.stories.tsx
> +  },
Done v2

2023-12-05 13:17 UTC, VictorPulzz commented on src/components/common/Button/index.tsx
> +      {!isLoading ? label : <Points size={30} />}
Done v2

2023-12-05 13:17 UTC, VictorPulzz commented on .storybook/stories/Loaders/Points.stories.tsx
> +  },
Done v2

2023-12-05 20:19 UTC, merged